const toggle=document.querySelector('.nav-toggle');
const nav=document.getElementById('nav');
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.focus();}});
const assetBase=location.pathname.includes('/menu/')||location.pathname.includes('/private-dining/')?'../assets/':'assets/';
const menuTabs=[...document.querySelectorAll('[data-menu]')];
let selectedMenu='dinner';
function renderMenu(key,updateHash=false){
 const data=window.BSTAR_MENUS?.[key];if(!data)return;selectedMenu=key;
 menuTabs.forEach(tab=>{const selected=tab.dataset.menu===key;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1;});
 document.getElementById('menu-panel').setAttribute('aria-labelledby','tab-'+key);
 document.getElementById('menu-title').textContent=data.title;
 document.getElementById('menu-kicker').textContent=data.kicker;
 document.getElementById('menu-description').textContent=data.description;
 const root=document.getElementById('menu-content');root.replaceChildren();
 for(const group of data.groups){const section=document.createElement('section');section.className='menu-category';const heading=document.createElement('h3');heading.textContent=group.title;section.append(heading);const grid=document.createElement('div');grid.className='menu-grid';for(const item of group.items){const article=document.createElement('article');article.className='menu-item';const row=document.createElement('div');row.className='menu-item-top';const name=document.createElement('h4');name.textContent=item.name;const price=document.createElement('span');price.className='price';price.textContent=item.price;row.append(name,price);article.append(row);if(item.description){const desc=document.createElement('p');desc.textContent=item.description;article.append(desc);}if(item.tags){const tags=document.createElement('span');tags.className='dietary';tags.textContent=item.tags;article.append(tags);}grid.append(article);}section.append(grid);root.append(section);}
 if(updateHash){try{history.replaceState(null,'','#'+key);}catch{location.hash=key;}}
}
if(menuTabs.length){renderMenu(window.BSTAR_MENUS[location.hash.slice(1)]?location.hash.slice(1):'dinner');menuTabs.forEach((tab,index)=>{tab.addEventListener('click',()=>renderMenu(tab.dataset.menu,true));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(index+1)%menuTabs.length;if(e.key==='ArrowLeft')next=(index-1+menuTabs.length)%menuTabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=menuTabs.length-1;if(next!==undefined){e.preventDefault();menuTabs[next].focus();renderMenu(menuTabs[next].dataset.menu,true);}});});window.addEventListener('hashchange',()=>renderMenu(location.hash.slice(1)||'dinner'));}
document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
document.getElementById('view-original')?.addEventListener('click',()=>{const src=assetBase+'menu-'+selectedMenu+'.webp';document.getElementById('original-image').src=src;document.getElementById('original-image').alt='Original B Star '+window.BSTAR_MENUS[selectedMenu].title;document.getElementById('menu-image-link').href=src;document.getElementById('original-title').textContent=window.BSTAR_MENUS[selectedMenu].title;document.getElementById('menu-dialog').showModal();});
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{const i=document.getElementById('gallery-image');i.src=b.dataset.photo;i.alt=b.dataset.caption;document.getElementById('gallery-title').textContent=b.dataset.caption;document.getElementById('gallery-dialog').showModal();}));
const form=document.getElementById('event-form');let inquiry='';
if(form){const date=form.elements.date;const now=new Date();date.min=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const f=new FormData(form);const value=k=>String(f.get(k)||'').trim();inquiry=['B STAR — PRIVATE DINING INQUIRY','',`Name: ${value('firstName')} ${value('lastName')}`,`Email: ${value('email')}`,`Phone: ${value('phone')}`,`Event: ${value('eventType')}`,`Guests: ${value('guests')}`,`Preferred date: ${value('date')||'Flexible'}`,`Time: ${value('time')}`,`Space: ${value('space')}`,`Budget: ${value('budget')}`,'',`Additional details: ${value('notes')||'None provided'}`,'','Consent: I agree to be contacted about this event inquiry.'].join('\n');document.getElementById('inquiry-summary').textContent=inquiry;document.getElementById('email-inquiry').href='mailto:eventsatbstar@gmail.com?subject='+encodeURIComponent('B Star event inquiry — '+value('eventType'))+'&body='+encodeURIComponent(inquiry);const review=document.getElementById('inquiry-review');review.hidden=false;review.focus();review.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});});
form.addEventListener('input',()=>{document.getElementById('inquiry-review').hidden=true;});
document.getElementById('download-inquiry').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([inquiry],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='B-Star-Event-Inquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
